packages:
  - github.com/graniticio/granitic/v2/ws/handler
  - bookapi/endpoint/book
  - bookapi/endpoint/author
  - bookapi/pkg/file

components:

  getBookLogic:
    type: book.GetBookLogic
    FileReader: ref:fileReaderWriter
  
  getAuthorLogic:
    type: author.GetAuthorLogic
  
  addBookLogic:
    type: book.AddBookLogic

  getBookHandler:
    type: handler.WsHandler
    HTTPMethod: GET
    Logic: ref:getBookLogic
    PathPattern: "^/books"
  
  addBookHandler:
    type: handler.WsHandler
    HTTPMethod: POST
    Logic: ref:addBookLogic
    PathPattern: "^/books"
  
  getAuthorHandler:
    type: handler.WsHandler
    HTTPMethod: GET
    Logic: ref:getAuthorLogic
    PathPattern: "^/authors"

  fileReaderWriter:
    type: file.ReaderWriter
    FileName: conf:Service.BookStore
  